# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.7"
services:
  www:
    build: #.
      context: ./servicios/www
      #dockerfile: phpApache.Dockerfile
    depends_on:
      - db
    ports: 
      - 80:80
    volumes:
      - ./servicios/www:/var/www/html
    links:
      - db 
    #networks:
      #- red_lamp
  db:
    image: "mysql:${MYSQL_VERSION}"
    container_name: mysqlHost
    ports: 
      - 3306:3306
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    #env_file:
      #- ./db.env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" 
    volumes:
      - ./servicios/db/dbname.sql:/docker-entrypoint-initdb.d/dbname.sql
      #- ./config/my_personalizada.cnf:/etc/mysql/conf.d/my_personalizada.cnf
      - mysql-data:/var/lib/mysql
    #networks:
      #- red_lamp
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}"
    links: 
      - db:db
    ports:
      - 8000:80
volumes:
  mysql-data:
#networks:
  #red_lamp: